version: "3.9"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-proxy
    # command: [nginx-debug, '-g', 'daemon off;'] # debug
    environment:
      DOMAINS: MP MPA MPL MPPL VDV VDVA
      MP: minepiece.fr
      MPA: adminer.minepiece.fr
      MPL: launcher.minepiece.fr
      MPPL: plugins.minepiece.fr
      VDV: gites-hautes-vosges.fr
      VDVA: adminer.gites-hautes-vosges.fr
    volumes:
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/certbot:/var/log/letsencrypt
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/acme-challenge:/var/www/certbot
      # - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      # - vps-public
      - minepiece-out
      - vdv-out
    # depends_on:
    #   - certbot

networks:
  vdv-out:
    name: vdv-out
    driver: bridge
    external: true
  minepiece-out:
    name: minepiece-out
    external: true
    driver: bridge
